Flussdiagramm Zahlungsmethode_speichern erstellt
Projektarbeiten/ProjectPlatypus pull request #15
Opened 2023-03-27 07:54 UTC by Codebreaker2k23

Flussdiagramm Zahlungsmethode_speichern erstellt

2023-03-28 06:56 UTC, Serinoxu requested changes
![image](https://user-images.githubusercontent.com/93043568/228152943-a2152f2f-d853-4607-8ac6-fb62309d3a24.png)

1. Pfeil von der Datenbank geht in die Falsche richtung. Die Daten werden ja abgespeichert und nicht geholt.

2. Stelle bitte auch den PHP Daten Senden Prozess in diesem Diagramm dar

3. Entweder definiere "Pflichtfelder" oder frage (oder überprüfe) diese einzeln ab, aber nicht beides.

2023-03-31 13:13 UTC, Serinoxu commented
![image](https://user-images.githubusercontent.com/93043568/229129473-b389200c-888b-420b-a443-3c59d7d5965f.png)
Noch umsetzten bitte

2023-05-09 18:33 UTC, Serinoxu requested changes
Bitte das Flussdiagramm an den vorhanden Prozess anpassen. Dies resultiert aus der Übernahme der Aufgabe. Prozess kann in PP-27 nachvollzogen werden.

2023-05-09 18:33 UTC, Serinoxu requested changes
Bitte das Flussdiagramm an den vorhanden Prozess anpassen. Dies resultiert aus der Übernahme der Aufgabe. Prozess kann in PP-27 nachvollzogen werden.

2023-05-09 18:33 UTC, Serinoxu requested changes
Bitte das Flussdiagramm an den vorhanden Prozess anpassen. Dies resultiert aus der Übernahme der Aufgabe. Prozess kann in PP-27 nachvollzogen werden.

2023-05-09 18:33 UTC, Serinoxu requested changes
Bitte das Flussdiagramm an den vorhanden Prozess anpassen. Dies resultiert aus der Übernahme der Aufgabe. Prozess kann in PP-27 nachvollzogen werden.

2023-05-09 18:33 UTC, Serinoxu requested changes
Bitte das Flussdiagramm an den vorhanden Prozess anpassen. Dies resultiert aus der Übernahme der Aufgabe. Prozess kann in PP-27 nachvollzogen werden.

2023-05-09 18:33 UTC, Serinoxu requested changes
Bitte das Flussdiagramm an den vorhanden Prozess anpassen. Dies resultiert aus der Übernahme der Aufgabe. Prozess kann in PP-27 nachvollzogen werden.

2023-05-09 18:33 UTC, Serinoxu requested changes
Bitte das Flussdiagramm an den vorhanden Prozess anpassen. Dies resultiert aus der Übernahme der Aufgabe. Prozess kann in PP-27 nachvollzogen werden.

2023-06-16 07:30 UTC, RibaruDev approved these changes

2023-06-23 08:55 UTC, GCoder002 commented
@Serinoxu passt das jetzt so wie der Stand der Dinge ist oder sind die Änderungen nicht so wie du dir das erhofft hast. Ist aus Entwiclkungssicht eh egal da die Funktion ja schon implementiert ist.

2024-03-15 09:11 UTC, merged