Flussdiagramm erstellt
Projektarbeiten/ProjectPlatypus pull request #31
Opened 2023-04-28 21:03 UTC by GCoder002

2023-05-02 13:43 UTC, GCoder002 commented
@Serinoxu könntest du das bitte noch reviewen

2023-05-02 13:44 UTC, GCoder002 commented
@RibaruDev könntest du noch bitte die von dir veränderten Änderungen pushen und die Review abscheßen?

2023-05-03 07:48 UTC, Serinoxu requested changes
![image](https://user-images.githubusercontent.com/93043568/235859108-7aebf703-59a4-4d0a-94bb-9f3ddc15527b.png)

Pfeil entfernen

2023-05-07 10:56 UTC, RibaruDev approved these changes
Pfeil entfernt und Ende hinzugefügt bei der Info

2023-05-07 10:56 UTC, merged